---
- hosts: all
  become: true

  tasks:
    - name: Gather EC2 facts
      ec2_facts:

    - name: Install Apache on RedHat or CentOS
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Apache on Debian or Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Enable and start Apache on RedHat or CentOS
      service:
        name: httpd
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

    - name: Enable and start Apache on Debian or Ubuntu
      service:
        name: apache2
        enabled: yes
        state: started
      when: ansible_os_family == "Debian"
